// File generated by FlutterFire CLI.
// This is a placeholder file. Run 'flutterfire configure' to generate the actual file.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxLTTxM3rTIht4pJxC8XExK8azA_GFQU',
    appId: '1:861969093408:web:c78e3b792a716f71e0bd45',
    messagingSenderId: '861969093408',
    projectId: 'gotnunchi-cc782',
    authDomain: 'gotnunchi-cc782.firebaseapp.com',
    storageBucket: 'gotnunchi-cc782.firebasestorage.app',
    measurementId: 'G-4CVCCVTWBV',
  );

  // TODO: Run 'flutterfire configure' to generate these values

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDpqZaRsuT8O9DbrHMIhiFS54tjbEVW3A',
    appId: '1:861969093408:android:5d40a51ac8d1054ce0bd45',
    messagingSenderId: '861969093408',
    projectId: 'gotnunchi-cc782',
    storageBucket: 'gotnunchi-cc782.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSbYFebwpVqmN-CVwHmJP4A5Di7e5gArY',
    appId: '1:861969093408:ios:fa5a7386beae5faee0bd45',
    messagingSenderId: '861969093408',
    projectId: 'gotnunchi-cc782',
    storageBucket: 'gotnunchi-cc782.firebasestorage.app',
    iosBundleId: 'com.gotnunchi.gotnunchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSbYFebwpVqmN-CVwHmJP4A5Di7e5gArY',
    appId: '1:861969093408:ios:fa5a7386beae5faee0bd45',
    messagingSenderId: '861969093408',
    projectId: 'gotnunchi-cc782',
    storageBucket: 'gotnunchi-cc782.firebasestorage.app',
    iosBundleId: 'com.gotnunchi.gotnunchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwxLTTxM3rTIht4pJxC8XExK8azA_GFQU',
    appId: '1:861969093408:web:7bc2ebe6fc29c983e0bd45',
    messagingSenderId: '861969093408',
    projectId: 'gotnunchi-cc782',
    authDomain: 'gotnunchi-cc782.firebaseapp.com',
    storageBucket: 'gotnunchi-cc782.firebasestorage.app',
    measurementId: 'G-Q4C7PLQEYP',
  );

}